#!/bin/bash
apm install atom-beautify
apm install atom-ctags
apm install atom-ternjs
apm install atom-ctags
apm install docblockr
apm install editorconfig
apm install file-icons
apm install git-blame
apm install git-plus
apm install highlight-selected
apm install language-apache
apm install language-docker
apm install linter
apm install linter-csslint
apm install linter-docker
apm install linter-eslint
apm install linter-htmlhint
apm install linter-js-yaml
apm install linter-jshint
apm install linter-jsonlist
apm install linter-rubocop
apm install linter-swagger
apm install linter-xmllint
apm install node-debugger
apm install pigments
apm install pretty-json
apm install react
apm install split-diff
apm install tree-view-git-status
